server:
  port: 8080

spring:
  rabbitmq:
    port: 5672
    host: localhost
    password: guest
    username: guest
  cloud:
    stream:
      bindings:
        person-out:
          destination: person
          contentType: application/json
        person-in:
          destination: person
          contentType: application/json
        person-out-2:
          destination: person2
          contentType: application/json
        person-in-2:
          destination: person2
          contentType: application/json
